package com.kunbo.xiwei.db.entity;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 9): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 9;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        CivilizedServiceFormDao.createTable(db, ifNotExists);
        CivilizedTypesDao.createTable(db, ifNotExists);
        ComplaintFormDao.createTable(db, ifNotExists);
        InspectionFormDao.createTable(db, ifNotExists);
        LaneTypesDao.createTable(db, ifNotExists);
        MonitorOndutyRecordeDao.createTable(db, ifNotExists);
        OverHighCarInDao.createTable(db, ifNotExists);
        OverHighCarOutDao.createTable(db, ifNotExists);
        SecurityCheckRecordeDao.createTable(db, ifNotExists);
        SecurityItemsDao.createTable(db, ifNotExists);
        SpecialFormDao.createTable(db, ifNotExists);
        SpecialTypesDao.createTable(db, ifNotExists);
        StationEmployeeDao.createTable(db, ifNotExists);
        StationOndutyRecordeDao.createTable(db, ifNotExists);
        TeamUsersDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        CivilizedServiceFormDao.dropTable(db, ifExists);
        CivilizedTypesDao.dropTable(db, ifExists);
        ComplaintFormDao.dropTable(db, ifExists);
        InspectionFormDao.dropTable(db, ifExists);
        LaneTypesDao.dropTable(db, ifExists);
        MonitorOndutyRecordeDao.dropTable(db, ifExists);
        OverHighCarInDao.dropTable(db, ifExists);
        OverHighCarOutDao.dropTable(db, ifExists);
        SecurityCheckRecordeDao.dropTable(db, ifExists);
        SecurityItemsDao.dropTable(db, ifExists);
        SpecialFormDao.dropTable(db, ifExists);
        SpecialTypesDao.dropTable(db, ifExists);
        StationEmployeeDao.dropTable(db, ifExists);
        StationOndutyRecordeDao.dropTable(db, ifExists);
        TeamUsersDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CivilizedServiceFormDao.class);
        registerDaoClass(CivilizedTypesDao.class);
        registerDaoClass(ComplaintFormDao.class);
        registerDaoClass(InspectionFormDao.class);
        registerDaoClass(LaneTypesDao.class);
        registerDaoClass(MonitorOndutyRecordeDao.class);
        registerDaoClass(OverHighCarInDao.class);
        registerDaoClass(OverHighCarOutDao.class);
        registerDaoClass(SecurityCheckRecordeDao.class);
        registerDaoClass(SecurityItemsDao.class);
        registerDaoClass(SpecialFormDao.class);
        registerDaoClass(SpecialTypesDao.class);
        registerDaoClass(StationEmployeeDao.class);
        registerDaoClass(StationOndutyRecordeDao.class);
        registerDaoClass(TeamUsersDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
