package com.kunbo.xiwei.db.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kunbo.xiwei.db.entity.CivilizedServiceForm;
import com.kunbo.xiwei.db.entity.CivilizedTypes;
import com.kunbo.xiwei.db.entity.ComplaintForm;
import com.kunbo.xiwei.db.entity.InspectionForm;
import com.kunbo.xiwei.db.entity.LaneTypes;
import com.kunbo.xiwei.db.entity.MonitorOndutyRecorde;
import com.kunbo.xiwei.db.entity.OverHighCarIn;
import com.kunbo.xiwei.db.entity.OverHighCarOut;
import com.kunbo.xiwei.db.entity.SecurityCheckRecorde;
import com.kunbo.xiwei.db.entity.SecurityItems;
import com.kunbo.xiwei.db.entity.SpecialForm;
import com.kunbo.xiwei.db.entity.SpecialTypes;
import com.kunbo.xiwei.db.entity.StationEmployee;
import com.kunbo.xiwei.db.entity.StationOndutyRecorde;
import com.kunbo.xiwei.db.entity.TeamUsers;

import com.kunbo.xiwei.db.entity.CivilizedServiceFormDao;
import com.kunbo.xiwei.db.entity.CivilizedTypesDao;
import com.kunbo.xiwei.db.entity.ComplaintFormDao;
import com.kunbo.xiwei.db.entity.InspectionFormDao;
import com.kunbo.xiwei.db.entity.LaneTypesDao;
import com.kunbo.xiwei.db.entity.MonitorOndutyRecordeDao;
import com.kunbo.xiwei.db.entity.OverHighCarInDao;
import com.kunbo.xiwei.db.entity.OverHighCarOutDao;
import com.kunbo.xiwei.db.entity.SecurityCheckRecordeDao;
import com.kunbo.xiwei.db.entity.SecurityItemsDao;
import com.kunbo.xiwei.db.entity.SpecialFormDao;
import com.kunbo.xiwei.db.entity.SpecialTypesDao;
import com.kunbo.xiwei.db.entity.StationEmployeeDao;
import com.kunbo.xiwei.db.entity.StationOndutyRecordeDao;
import com.kunbo.xiwei.db.entity.TeamUsersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig civilizedServiceFormDaoConfig;
    private final DaoConfig civilizedTypesDaoConfig;
    private final DaoConfig complaintFormDaoConfig;
    private final DaoConfig inspectionFormDaoConfig;
    private final DaoConfig laneTypesDaoConfig;
    private final DaoConfig monitorOndutyRecordeDaoConfig;
    private final DaoConfig overHighCarInDaoConfig;
    private final DaoConfig overHighCarOutDaoConfig;
    private final DaoConfig securityCheckRecordeDaoConfig;
    private final DaoConfig securityItemsDaoConfig;
    private final DaoConfig specialFormDaoConfig;
    private final DaoConfig specialTypesDaoConfig;
    private final DaoConfig stationEmployeeDaoConfig;
    private final DaoConfig stationOndutyRecordeDaoConfig;
    private final DaoConfig teamUsersDaoConfig;

    private final CivilizedServiceFormDao civilizedServiceFormDao;
    private final CivilizedTypesDao civilizedTypesDao;
    private final ComplaintFormDao complaintFormDao;
    private final InspectionFormDao inspectionFormDao;
    private final LaneTypesDao laneTypesDao;
    private final MonitorOndutyRecordeDao monitorOndutyRecordeDao;
    private final OverHighCarInDao overHighCarInDao;
    private final OverHighCarOutDao overHighCarOutDao;
    private final SecurityCheckRecordeDao securityCheckRecordeDao;
    private final SecurityItemsDao securityItemsDao;
    private final SpecialFormDao specialFormDao;
    private final SpecialTypesDao specialTypesDao;
    private final StationEmployeeDao stationEmployeeDao;
    private final StationOndutyRecordeDao stationOndutyRecordeDao;
    private final TeamUsersDao teamUsersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        civilizedServiceFormDaoConfig = daoConfigMap.get(CivilizedServiceFormDao.class).clone();
        civilizedServiceFormDaoConfig.initIdentityScope(type);

        civilizedTypesDaoConfig = daoConfigMap.get(CivilizedTypesDao.class).clone();
        civilizedTypesDaoConfig.initIdentityScope(type);

        complaintFormDaoConfig = daoConfigMap.get(ComplaintFormDao.class).clone();
        complaintFormDaoConfig.initIdentityScope(type);

        inspectionFormDaoConfig = daoConfigMap.get(InspectionFormDao.class).clone();
        inspectionFormDaoConfig.initIdentityScope(type);

        laneTypesDaoConfig = daoConfigMap.get(LaneTypesDao.class).clone();
        laneTypesDaoConfig.initIdentityScope(type);

        monitorOndutyRecordeDaoConfig = daoConfigMap.get(MonitorOndutyRecordeDao.class).clone();
        monitorOndutyRecordeDaoConfig.initIdentityScope(type);

        overHighCarInDaoConfig = daoConfigMap.get(OverHighCarInDao.class).clone();
        overHighCarInDaoConfig.initIdentityScope(type);

        overHighCarOutDaoConfig = daoConfigMap.get(OverHighCarOutDao.class).clone();
        overHighCarOutDaoConfig.initIdentityScope(type);

        securityCheckRecordeDaoConfig = daoConfigMap.get(SecurityCheckRecordeDao.class).clone();
        securityCheckRecordeDaoConfig.initIdentityScope(type);

        securityItemsDaoConfig = daoConfigMap.get(SecurityItemsDao.class).clone();
        securityItemsDaoConfig.initIdentityScope(type);

        specialFormDaoConfig = daoConfigMap.get(SpecialFormDao.class).clone();
        specialFormDaoConfig.initIdentityScope(type);

        specialTypesDaoConfig = daoConfigMap.get(SpecialTypesDao.class).clone();
        specialTypesDaoConfig.initIdentityScope(type);

        stationEmployeeDaoConfig = daoConfigMap.get(StationEmployeeDao.class).clone();
        stationEmployeeDaoConfig.initIdentityScope(type);

        stationOndutyRecordeDaoConfig = daoConfigMap.get(StationOndutyRecordeDao.class).clone();
        stationOndutyRecordeDaoConfig.initIdentityScope(type);

        teamUsersDaoConfig = daoConfigMap.get(TeamUsersDao.class).clone();
        teamUsersDaoConfig.initIdentityScope(type);

        civilizedServiceFormDao = new CivilizedServiceFormDao(civilizedServiceFormDaoConfig, this);
        civilizedTypesDao = new CivilizedTypesDao(civilizedTypesDaoConfig, this);
        complaintFormDao = new ComplaintFormDao(complaintFormDaoConfig, this);
        inspectionFormDao = new InspectionFormDao(inspectionFormDaoConfig, this);
        laneTypesDao = new LaneTypesDao(laneTypesDaoConfig, this);
        monitorOndutyRecordeDao = new MonitorOndutyRecordeDao(monitorOndutyRecordeDaoConfig, this);
        overHighCarInDao = new OverHighCarInDao(overHighCarInDaoConfig, this);
        overHighCarOutDao = new OverHighCarOutDao(overHighCarOutDaoConfig, this);
        securityCheckRecordeDao = new SecurityCheckRecordeDao(securityCheckRecordeDaoConfig, this);
        securityItemsDao = new SecurityItemsDao(securityItemsDaoConfig, this);
        specialFormDao = new SpecialFormDao(specialFormDaoConfig, this);
        specialTypesDao = new SpecialTypesDao(specialTypesDaoConfig, this);
        stationEmployeeDao = new StationEmployeeDao(stationEmployeeDaoConfig, this);
        stationOndutyRecordeDao = new StationOndutyRecordeDao(stationOndutyRecordeDaoConfig, this);
        teamUsersDao = new TeamUsersDao(teamUsersDaoConfig, this);

        registerDao(CivilizedServiceForm.class, civilizedServiceFormDao);
        registerDao(CivilizedTypes.class, civilizedTypesDao);
        registerDao(ComplaintForm.class, complaintFormDao);
        registerDao(InspectionForm.class, inspectionFormDao);
        registerDao(LaneTypes.class, laneTypesDao);
        registerDao(MonitorOndutyRecorde.class, monitorOndutyRecordeDao);
        registerDao(OverHighCarIn.class, overHighCarInDao);
        registerDao(OverHighCarOut.class, overHighCarOutDao);
        registerDao(SecurityCheckRecorde.class, securityCheckRecordeDao);
        registerDao(SecurityItems.class, securityItemsDao);
        registerDao(SpecialForm.class, specialFormDao);
        registerDao(SpecialTypes.class, specialTypesDao);
        registerDao(StationEmployee.class, stationEmployeeDao);
        registerDao(StationOndutyRecorde.class, stationOndutyRecordeDao);
        registerDao(TeamUsers.class, teamUsersDao);
    }
    
    public void clear() {
        civilizedServiceFormDaoConfig.clearIdentityScope();
        civilizedTypesDaoConfig.clearIdentityScope();
        complaintFormDaoConfig.clearIdentityScope();
        inspectionFormDaoConfig.clearIdentityScope();
        laneTypesDaoConfig.clearIdentityScope();
        monitorOndutyRecordeDaoConfig.clearIdentityScope();
        overHighCarInDaoConfig.clearIdentityScope();
        overHighCarOutDaoConfig.clearIdentityScope();
        securityCheckRecordeDaoConfig.clearIdentityScope();
        securityItemsDaoConfig.clearIdentityScope();
        specialFormDaoConfig.clearIdentityScope();
        specialTypesDaoConfig.clearIdentityScope();
        stationEmployeeDaoConfig.clearIdentityScope();
        stationOndutyRecordeDaoConfig.clearIdentityScope();
        teamUsersDaoConfig.clearIdentityScope();
    }

    public CivilizedServiceFormDao getCivilizedServiceFormDao() {
        return civilizedServiceFormDao;
    }

    public CivilizedTypesDao getCivilizedTypesDao() {
        return civilizedTypesDao;
    }

    public ComplaintFormDao getComplaintFormDao() {
        return complaintFormDao;
    }

    public InspectionFormDao getInspectionFormDao() {
        return inspectionFormDao;
    }

    public LaneTypesDao getLaneTypesDao() {
        return laneTypesDao;
    }

    public MonitorOndutyRecordeDao getMonitorOndutyRecordeDao() {
        return monitorOndutyRecordeDao;
    }

    public OverHighCarInDao getOverHighCarInDao() {
        return overHighCarInDao;
    }

    public OverHighCarOutDao getOverHighCarOutDao() {
        return overHighCarOutDao;
    }

    public SecurityCheckRecordeDao getSecurityCheckRecordeDao() {
        return securityCheckRecordeDao;
    }

    public SecurityItemsDao getSecurityItemsDao() {
        return securityItemsDao;
    }

    public SpecialFormDao getSpecialFormDao() {
        return specialFormDao;
    }

    public SpecialTypesDao getSpecialTypesDao() {
        return specialTypesDao;
    }

    public StationEmployeeDao getStationEmployeeDao() {
        return stationEmployeeDao;
    }

    public StationOndutyRecordeDao getStationOndutyRecordeDao() {
        return stationOndutyRecordeDao;
    }

    public TeamUsersDao getTeamUsersDao() {
        return teamUsersDao;
    }

}
